### ISSUE TITLE
Ecrasement info

### ISSUE THREAD

**Issue by LionelGott** [impulsio/MerosSync#4]
Salut, dans Jeedom, lorsque je fais le lien avec mon compte Meross les données sont toujours écrasées par "Switch 1", "Switch 2", etc.
Comment faire pour que les champs que je modifie dans Jeedom ne soient pas écrasés par l'actualisation du plugin svp ?
![Capture d’écran 2023-01-12 185318](https://user-images.githubusercontent.com/122558729/212142478-e7094537-a164-48b5-ad87-35a7d9cf84e6.jpg)
Merci,
Lionel

**Comment by impulsio** [comment]
Bonjour,
Je vais regarder cela. D'autant plus que meross propose aussi de modifier le nom de chaque prise via l'application. A voir ce qu'il faut favoriser.

**Comment by impulsio** [comment]
![Screenshot_20230113-163007](https://user-images.githubusercontent.com/33810912/212357516-ee6e46dd-b87e-4904-8d52-7f982165e2a2.png)

**Comment by LionelGott** [comment]
Hello, 
oui tout à fait, j'ai déjà modifié le nom de chaque prise de la multiprise dans l'appli MEROSS.

![Screenshot_2023-01-13-16-39-08-43_56b7547d8e4eb7c7b8ab580c8df8134f](https://user-images.githubusercontent.com/122558729/212359425-00e02c34-9279-447d-9877-d852922e48bd.jpg)

**Comment by impulsio** [comment]
Donc je vais corriger pour prendre les noms de merosz alors ce sera bien !

**Comment by LionelGott** [comment]
ouaho ! aussi vite !! Je ne m'attendais pas à une si grande réactivité :)
Merci pour ton travail ;)

**Comment by impulsio** [comment]
Ce n'est pas faire encore 😆 je le ferai ce weekend 😉

Le ven. 13 janv. 2023, 16:45, LionelGott ***@***.***> a
écrit :

**Comment by LionelGott** [comment]
C'est déjà très bien. Merci à toi :)

**Comment by impulsio** [comment]
Bonjour,
C'est corrigé via le nouveau commit https://github.com/impulsio/MerosSync/commit/f823b899f62959b7951bff1c9f095a0ae51cd3e2

Voilà le résultat de mon côté :
![image](https://user-images.githubusercontent.com/33810912/212477565-8c465279-6299-4630-ac30-05c7392c1dc2.png)

![image](https://user-images.githubusercontent.com/33810912/212477596-f6fac588-30cc-4404-a183-7245e71d0879.png)

Les informations proviennent de meross donc à ne pas renommer ;)

Dès la disponibilité côté jeedom je te laisserai vérifier que tout est ok pour toi !

Bonne journée,
Jérôme

**Comment by LionelGott** [comment]
Super Jérôme, merci je te tiendrai au courant dès réception de la mise à jour 👍
Bon Week end
Lionel

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LionelGott** [comment]
Salut Jérôme, j’ai vérifié ce matin c’est parfait 👍
Au plaisir d’échanger avec toi.
Lionel

Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Lionel GOTTRAU ***@***.***>
Envoyé : Saturday, January 14, 2023 4:58:34 PM
À : impulsio/MerosSync ***@***.***>; impulsio/MerosSync ***@***.***>
Cc : Author ***@***.***>
Objet : Re: [impulsio/MerosSync] Ecrasement info (Issue #4)

Super Jérôme, merci je te tiendrai au courant dès réception de la mise à jour 👍
Bon Week end
Lionel

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by impulsio** [comment]
Parfait tout ça !
Bonne journée
