### ISSUE TITLE
Log In issue

### ISSUE THREAD

**Issue by francbad** [impulsio/MerosSync#9]
Bonjour depuis ce matin 8h20 impossible de se connecter au compte meross.

Le log montre : 
[2024-07-09 14:00:08] DEBUG [meross_iot.http_api] : Response Status Code: 200
[2024-07-09 14:00:08] INFO [meross_iot.http_api] : Login successful against https://iotx-eu.meross.com
[2024-07-09 14:00:08] ERROR [DemonPython] : 'mfaLockExpire'
[2024-07-09 14:00:08] DEBUG [DemonPython] : Ecriture du PID 13376 dans /tmp/jeedom/MerosSync/errordaemon.pid
'mfaLockExpire'

il semble y avoir un soucis authentification mais j'ai vérifié le mot de passe et cela semble ok ... est ce que l'api meross a changé ?

**Comment by impulsio** [comment]
Bonjour,

Le problème est nouveau apparemment et connu sur le code que j’utilise pour MerossSync. Voici l’erreur remonté sur le module python : [KeyError: ‹ mfaLockExpire › · Issue #385 · albertogeniola/MerossIot · GitHub 1](https://github.com/albertogeniola/MerossIot/issues/385)

Le seul moyen pour l’instant que j’ai c’est de modifier directement le module python qui fait défaut : attention cela est réservé aux utilisateurs de jeedom aguerris qui savent ce qu’ils font :slight_smile: Solution testé sur mon jeedom et ça corrige le problème.

`cd /usr/local/lib/python3.9/dist-packages/meross_iot`

Puis prendre les droits admin :

    `sudo su -`

Faire un

    `vi http_api.py`

puis modifier la ligne 273 pour ajouter cette ligne :

        `response_data["mfaLockExpire"]=""`

!!! Attention : bien mettre 2 tabulations sinon vous allez avoir des erreurs !!!

Si vous avez fait une erreur vous pourrez toujours relancer l’installation du module.

Ou attendre une mise à jour du module.

Bonne soirée !
Jérôme

**Comment by francbad** [comment]
je m'y tente mais par l'interface graphique :-) de jeedom je vomi VI

**Comment by impulsio** [comment]
Sinon il y a nano
Je ne suis pas sûr que le fichier soit modifiable via jeedom

**Comment by francbad** [comment]
effectivement il ne l'est pas, je m'y pencherai une autre fois alors car j'ai vraiment de très mauvais souvenir des éditeurs en ligne de commande !

merci en tout cas !

**Comment by impulsio** [comment]
Oui. Le problème c'est qu'il faut modifier un fichier système et via sftp
c'est bloqué car il faut passe en sudo.

**Comment by impulsio** [comment]
Bonjour,
 une nouvelle version du plugin MerosSync est disponible et corrige le problème.
Bonne journée,
Jérôme

**Comment by francbad** [comment]
merci, visiblement c'était revenu hier apres midi sans que je change quoi que ce soit ....
